#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
    . /usr/share/dbconfig-common/dpkg/config

    dbc_dbtypes="pgsql, mysql"
    dbc_authmethod_user="password"

    . /usr/share/dbconfig-common/dpkg/config

    dbc_go movim $@
fi

db_input high movim/httpserver || true
db_go || true

exit 0
