name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - master

jobs:
  docker_publish:
    runs-on: "ubuntu-24.04"

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
